var board_names = {
	Anniversary 	: '酒井十五年',
	cling_shop			: '附件测试',
	Goodbye					: '对不起我先走了',
	newcomers				: '新手上路',
	notice					: '广而告之',
	spirit					: '酒井文集',
	sysop						: '站长的工作室',
	test						:	'试一下下啦',
	vote						: '本站各项投票与结果',
	Address_book		: '有朋自远方来',
	criticism_center: '系学生工作',
	Express_9				: '酒井特快',
	four_plus_two		: '推研专版',
	graduate				: '毕业生',
	ita							: '信息技术协会',
	J2000						: '从零开始',
	J2EndlessEmotion:	'计二年华',
	junior					: '大三生活',
	Post_Graduate		: '博硕之家',
	sophomore				: '新生力量',
	student_festival:	'学生节',
	study_experience:	'学习经验',
	circuit					: '硬件设计与调试',
	Delphi					: 'Delphi',
	hacker_cracker	: '黑客和饼干',
	Hardware				:	'硬件架构',
	java						: 'Java语言',
	MS_Dev					:	'从微软到巨硬',
	PC_Games				: '游戏人生',
	program					: '编程技术',
	software				: '新潮软体',
	innovation			: '酒井法子',
	network					: '网路骑兵',
	Recommend_Addr	: '网址推荐',
	FreeOS					: '电脑迷的OS',
	road_ahead			: '未来之路',
	second_hand			: '二道贩子',
	e_note					: '毁人不倦',
	foreign_language: '外语角',
	Science					: '学术科学',
	book						: '好书大家读',
	cla_literature	: '古典文学',
	couplet					: '对联',
	Emprise_and_SF	: '武侠科幻',
	Fantasy					: '奇幻国度',
	linguist				: '语言学',
	literature			: '诗歌散文',
	novel						: '纸上人生',
	art							: '艺术殿堂',
	campus_song			: '校园音乐',
	cla_music				: '古典情怀',
	computer_art		: '电脑艺术',
	Dance						: '与狼共舞',
	photography			: '摄影',
	pop_music				: '流行时空',
	rock_music			: '摇滚天地',
	history					: '上下五千年',
	philosophy			: '智慧海',
	health					: '为祖国健康工作五十年',
	military				: '军事观察',
	study_abroad		: '飞跃重洋',
	baseball				: '棒球奔腾',
	basketball			: '篮球天地',
	chess_card			: '棋牌乐',
	dept_sports			: '酒井体坛',
	PremierLeague		: '酒超联赛',
	soccer					: '绿茵风云',
	sports					: '体育大看台',
	amusement				: '休闲运动',
	collector				: '收藏家',
	comic						: '漫漫风行',
	Fashion					: '流行风',
	food						: '大嘴吃四方',
	guess						: '猜猜看',
	humor						: '搞一搞，笑一笑',
	movies					: '露天剧场',
	MUD							: '泥潭乐园',
	travel					: '环顾四方',
	TV							: '电视剧场',
	TV_Games				: '电玩小子',
	emotion					: '情感小屋',
	Family					: '我爱我家',
	Girl_and_Boy		: '男孩子★女孩子',
	Male						: '性别男，征名中。',
	notepad					: '酸甜苦辣留言板',
	ONce_More				: '酒别重逢',
	ghost_story			: '恐怖故事',
	happy_birthday	: '你快乐，所以我快乐！',
	psychology			: '心理热线',
	tea_room				: '酒井茶馆',
	chn_news				: '神州风采',
	int_news				: '海外星云'
};
	
	